### ISSUE TITLE
Error when executing code sample

### ISSUE THREAD

**Issue by PMAxelDelsol** [ruby-rdf/shex#4]
The error `undefined method 'lexical=' for #<RDF::URI:0x000055e00d5719d8> (NoMethodError)` is raised when trying to execute the following code (extracted from the README).

The rdf gem version used is 3.1.15. 
I also add the stack trace in the issue, hopefully it can help.
[stack_trace.txt](https://github.com/ruby-rdf/shex/files/7193965/stack_trace.txt)

```ruby
# frozen_string_literal: true

require 'rdf/turtle'
require 'shex'

shexc =  %(
  PREFIX doap:  <http://usefulinc.com/ns/doap#>
  PREFIX dc:    <http://purl.org/dc/terms/>
  <TestShape> EXTRA a {
    a doap:Project;
    (doap:name;doap:description|dc:title;dc:description)+;
    doap:category*;
    doap:developer IRI;
    doap:implements    [<http://shex.io/shex-semantics/>]
  }
)

graph = RDF::Graph.load("etc/doap.ttl")
schema = ShEx.parse(shexc)
map = {
  "https://rubygems.org/gems/shex" => "TestShape"
}
schema.satisfies?("https://rubygems.org/gems/shex", graph, map)
```

**Comment by gkellogg** [comment]
Looks like a missing dependency that is satisfied when running through the bundler. I’ll check it out.

**Comment by gkellogg** [comment]
@PMAxelDelsol although there were some other minor issues this exposed, the main problems were that the examples were out of date. Try again from the develop branch of the repo and I can release an updated gem.

**Comment by PMAxelDelsol** [comment]
I confirm everything works perfectly from the develop branch.

Thank you very much !
