### ISSUE TITLE
CLI support?

### ISSUE THREAD

**Issue by dpriskorn** [ruby-rdf/shex#5]
Hi, I'm new to Ruby. 
Would it be possible to execute this validation from the CLI?
If not, could you add cli support?
See https://www.wikidata.org/wiki/User:So9q/shexjs for how shexjs enables cli support

**Comment by gkellogg** [comment]
See the [README](https://github.com/ruby-rdf/shex) for how to use the [Command Line](https://github.com/ruby-rdf/shex#command-line). For example:


    rdf shex https://raw.githubusercontent.com/ruby-rdf/shex/develop/etc/doap.ttl \
      --schema https://raw.githubusercontent.com/ruby-rdf/shex/develop/etc/doap.shex \
      --focus https://rubygems.org/gems/shex
